### PR TITLE
Elijah/refactor character code

### LINKED ISSUE #19: Player Move Action
When the player switches from performing a movement action to any other action, reduce the player's actions left by one.

### LINKED ISSUE #76: Refactor Code for Encapsulation
The code needs to be cleaner, and forcing encapsulation is a great way to clean up the code.

### LINKED ISSUE #83: Simplify Actions
Each action can be performed one at a time.  So a character may not move into a square containing food, pick up the food, and then continue moving.  That way, the code logic is simple, and it gives a simple structure for the player to follow.

### LINKED ISSUE #84: Collect Food Button
When the player starts their turn, show a button to collect the food.  When the button is pressed, the player's actions reduce and they collect a morsel.  Starting the player's turn includes after using an action.

### PR DESCRIPTION
**Pull request by Endermandels**
Simplified code quite a bit by funneling most of the player inputs into the Battle Scene script.  Read the commit message for more details on what was changed.

resolves #84
resolves #83
resolves #76
resolves #19

### CODE REVIEW

**Comment by Endermandels** [comment]
ERROR MERGING WITH MAIN: The Quit to Main Menu Button no longer works.  This will need to be fixed.

**Comment by Endermandels** [comment]
I think I need to learn how to merge into main properly XD

It works now.

**Review by NateShaw2 — COMMENTED** [review]
Overall I like the new refactored code but I do have some questions.

- Was the deletion of the new options menu intentional? 
I notice that the files responsible for the recent options menu with the sound/controller tab and the working large text/dyslexic friendly font was deleted. Just wanted to make sure if this was intentional or not. If so then I would let Emma know about this.

- Should the player be allowed to change their movement position after already moving?
Let's say that the player moves their character two tiles north but then quickly realizes that they want to move two tiles west instead. Should the player be able to change their position if it would of been an initially valid tile and they did not perform any different action (ex. attacking/collecting morsel) yet? If so then I do have an idea on how to make this work and can work on it in a separate branch once this PR is merged.

**Comment by NateShaw2** [comment]
Emma's new option menu is working again. Although the collect food button and finish movement button are not affected by the large text and dyslexic-friendly font option and will need to be fixed later.

**Pull request merged**
