### PR TITLE
Fully-Functional Settings/Options Menu

### PR DESCRIPTION
**Pull request by ecclesemma**
The Options menu now works, users can toggle large text size and a dyslexia friendly font. The addition of an autoloader file named Settings allows for the storage of global user settings variables, ensuring persistence across scenes.

### CODE REVIEW

**Comment by DanT52** [comment]
Looks good just i think the options should be hidden on ready by default, because it currently was going to the options every time I went back to the menu.

**Review by NateShaw2 — COMMENTED** [review]
Something that I like to add is that I noticed that the dyslexia-friendly option did not apply to the "quit to main menu" button and the large text option did not apply to the "start", "options", or "exit" for the demo screen.

I'm also wondering if the text for "Slyvia Battle Demo" is already dyslexia-friendly or not since the dyslexia-friendly option doesn't change the font for "Slyvia Battle Demo".

**Review by NateShaw2 — COMMENTED** [review]
I like the design of the new tabs in the options menu, and it seems that all of the previous bugs were fixed, although I have some questions regarding the tabs. Are the sound tab and controller tab supposed to be fully functional in this PR, or are they gonna be worked on as separate features in separate branches? If they are separate issues, then I would create an issue for the sound tab where you either assign yourself or Joey to work on it and create an issue for the controller tab and assign yourself to that. If the sound tab and controller tab are gonna be worked on in separate branches, then I think that this PR is ready to merge.

**Comment by ecclesemma** [comment]
Yes, @NateShaw2 the other tabs will be implemented in a future update. I'll talk to Joey about the sound tab. The option to remap controls is issue #30 and one of my final functional requirements.

**Pull request merged**
